// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/List/Sections.tsx";
import * as $$$1 from "./loaders/product/getSellers.ts";
import * as $$$2 from "./loaders/product/getSimilars.tsx";
import * as $$$3 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$$$$0 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$1 from "./sections/Layout/Grid.tsx";
import * as $$$$$$2 from "./sections/Layout/Flex.tsx";
import * as $$$$$$3 from "./sections/Layout/Container.tsx";
import * as $$$$$$4 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$5 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$6 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$7 from "./sections/Theme/Theme.tsx";
import * as $$$$$$8 from "./sections/Content/Faq.tsx";
import * as $$$$$$9 from "./sections/Content/Benefits.tsx";
import * as $$$$$$10 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$11 from "./sections/Content/Logos.tsx";
import * as $$$$$$12 from "./sections/Header/Header.tsx";
import * as $$$$$$13 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$14 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$15 from "./sections/Layout/Container.tsx";
import * as $$$$$$16 from "./sections/Layout/Flex.tsx";
import * as $$$$$$17 from "./sections/Layout/Grid.tsx";
import * as $$$$$$18 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$19 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$20 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$21 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$22 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$23 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$24 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$25 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$26 from "./sections/Product/ProductMain.tsx";
import * as $$$$$$27 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$28 from "./sections/Product/NotFound.tsx";
import * as $$$$$$29 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$30 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$31 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$32 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$33 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$34 from "./sections/Footer/Footer.tsx";
import * as $$$$$$$$$0 from "./actions/newsletter/record.ts";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "loaders": {
    "deco-sites/ramarim/loaders/Layouts/ProductCard.tsx": $$$3,
    "deco-sites/ramarim/loaders/List/Sections.tsx": $$$0,
    "deco-sites/ramarim/loaders/product/getSellers.ts": $$$1,
    "deco-sites/ramarim/loaders/product/getSimilars.tsx": $$$2,
  },
  "sections": {
    "deco-sites/ramarim/sections/Category/CategoryBanner.tsx": $$$$$$20,
    "deco-sites/ramarim/sections/Category/CategoryList.tsx": $$$$$$21,
    "deco-sites/ramarim/sections/Content/Benefits.tsx": $$$$$$9,
    "deco-sites/ramarim/sections/Content/Faq.tsx": $$$$$$8,
    "deco-sites/ramarim/sections/Content/Logos.tsx": $$$$$$11,
    "deco-sites/ramarim/sections/Content/Testimonials.tsx": $$$$$$10,
    "deco-sites/ramarim/sections/Footer/Footer.tsx": $$$$$$34,
    "deco-sites/ramarim/sections/Gallery.tsx": $$$$$$19,
    "deco-sites/ramarim/sections/Header/Header.tsx": $$$$$$12,
    "deco-sites/ramarim/sections/Images/Carousel.tsx": $$$$$$16,
    "deco-sites/ramarim/sections/Images/ImageGallery.tsx": $$$$$$13,
  },
  "actions": {
    "deco-sites/ramarim/actions/newsletter/record.ts": $$$$$$$$$0,
  },
  "apps": {
    "deco-sites/ramarim/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/ramarim/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/ramarim",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
